apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoKCSJhdXRocyI6IHsKCQkiZ2hjci5pbyI6IHsKCQkJImF1dGgiOiAiWW1sdGEyRXdPVHBuYUhCZlVGWlRhVkp6TkVsSlZtTmlSa1ZGUm1OMFV6WXdXVE5DTlZWaE0zTmpNRUpMUVhGcSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==

type: kubernetes.io/dockerconfigjson
