apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: Ymlta2EwOTpnaHBfUFZTaVJzNElJVmNiRkVFRmN0UzYwWTNCNVVhM3NjMEJLQXFq
type: kubernetes.io/dockerconfigjson
